spring:
  application:
    name: drools
  profiles:
    group:
      local: local
      dev:  dev
      test: test
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 20GB
      enabled: true



---
server:
  port: 8020
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://huring.grib-iot.com:9506/drools_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: grib
    password: grib12!@
    hikari:
      max-lifetime: 600000
      idle-timeout: 300000
      minimum-idle: 2
      maximum-pool-size: 10
      validation-timeout: 3000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
  jwt:
    secret: $2a$10$8.Q.gxUmGJP36W.uzANIsen8h.gmWJnfQAvHRH6BAIZ7pdYwM/hxG
  logging:
    level:
      root: debug
      kr.co.grib.drools: debug
  data:
    redis:
      host: huring.grib-iot.com
      port: 9507


---
server:
  port: 9627
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://192.168.0.240:3306/drools_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: grib
    password: grib12!@
    hikari:
      max-lifetime: 600000
      idle-timeout: 300000
      minimum-idle: 2
      maximum-pool-size: 10
      validation-timeout: 3000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
  jwt:
    secret: $2a$10$8.Q.gxUmGJP36W.uzANIsen8h.gmWJnfQAvHRH6BAIZ7pdYwM/hxG
  logging:
    level:
      root: debug
      kr.co.grib.drools: info
  data:
    redis:
      host: 192.168.0.240
      port: 6379

---
server:
  port: 8040
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jwt:
    secret: $2a$10$nz4X/L.yxOIij476l/R3POjlin.joh6ykIONIAUmbytgraegGVZty
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect




---
drools:
  template:
    prefix: templates/rules/
    suffix: .txt
    encoding: UTF-8
    order: 1
    fileName: rule-templates

---
spring doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method


