spring:
  application:
    name: drools
  profiles:
    group:
      local: local
      dev:  dev
      test: test
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 20GB
      enabled: true

---
server:
  port: 8020
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://192.168.0.240:3306/aiot_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: grib
    password: grib12!@
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  logging:
    level:
      root: debug
      kr.co.grib.drools: debug


---
server:
  port: 8030
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://192.168.0.240:3306/aiot_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: grib
    password: grib12!@
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  logging:
    level:
      root: info
      kr.co.grib.drools: info

---
server:
  port: 8040
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect



---
drools:
  rule-path: rules/rule.drl
  template:
    prefix: templates/
    suffix: .drl
    encoding: UTF-8
    order: 1


